In [2]:
# College Settlement dara modification
# By Marzieh Shiva Khosravi
# to get the "03 - Weather Station Modified" & "04 - Water Quantity Modified"

# Importing the packages
import pandas as pd
import numpy as np
import os

In [2]:
# working directory
os.getcwd()

'C:\\Users\\mkhosrav\\Data Modification'

In [16]:
# Reading the Excell data file
RawData = pd.read_excel('20190101 - 20190331 College Settlement Logger Data.xlsx')
RawData.head()

,Date/Time,RSS,Battery,Rain,WindSpeed,WindDirection,Temp,Humidity,BaroPressure,Bubbler1Level,...,Bubbler4Level,Bubbler4Pressure,Bubbler4Temp,Radiation,College Settlement > Cell 1 > Water Level (cm) (cm),College Settlement > Cell 2 > Water Level (cm) (cm),College Settlement > Cell 3 > Water Level (cm) (cm),College Settlement > Flume > Water Level (cm) (cm),College Settlement > Statistics > Station Health (%),College Settlement: Outflow (L/sec)
0,2019-03-31 23:55:00,NaN,NaN,NaN,4.8,56.0,34.6,49.0,29.65,0.61,...,0.03,0.04,2.2,0.24,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-03-31 23:50:00,NaN,NaN,NaN,4.2,41.0,34.8,49.0,29.65,0.61,...,0.03,0.04,2.3,0.24,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-03-31 23:45:00,NaN,12.41,NaN,9.0,354.0,34.9,48.0,29.65,0.61,...,0.03,0.04,2.4,0.24,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-03-31 23:40:00,NaN,NaN,NaN,4.8,52.0,35.2,48.0,29.64,0.61,...,0.03,0.04,2.5,0.24,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-03-31 23:35:00,NaN,NaN,NaN,4.2,56.0,35.3,48.0,29.64,0.61,...,0.03,0.04,2.6,0.24,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
# Reading the CSV data file
RawData = pd.read_csv("20210729 - 20210828 College Settlement Logger Data.csv")
RawData.head()

,Timestamp,College Settlement > RSSI,College Settlement > Battery,College Settlement > Rain Bucket > Rain (in),College Settlement > Weather Station (MSO) > Wind Speed (mph) (MPH),College Settlement > Weather Station (MSO) > Wind Direction (deg) (°),College Settlement > Weather Station (MSO) > Temperature (F) (°F),College Settlement > Weather Station (MSO) > Relative Humidity (%) (%),College Settlement > Weather Station (MSO) > Barometric Pressure (inHg),College Settlement > Cell 1 > Water Level (m),...,College Settlement > Flume > Water Level (m) (m),College Settlement > Flume > Pressure (psi) (psi),College Settlement > Flume > Temperature (C) (°C),College Settlement > Pyronometer (W/m^2) > Radiation (W/m²),College Settlement > Cell 1 > Water Level (cm) (cm),College Settlement > Cell 2 > Water Level (cm) (cm),College Settlement > Cell 3 > Water Level (cm) (cm),College Settlement > Flume > Water Level (cm) (cm),College Settlement > Statistics > Station Health (%),College Settlement: Outflow (L/sec)
0,2021-08-28 23:55:00,NaN,NaN,NaN,0.6,126.0,66.5,87.0,29.89,0.76,...,0.04,0.05,19.0,0.26,76.0,25.0,10.0,4.0,NaN,0.72
1,2021-08-28 23:50:00,NaN,NaN,NaN,0.6,114.0,66.5,87.0,29.89,0.76,...,0.04,0.05,19.0,0.26,76.0,25.0,10.0,4.0,99.4,0.72
2,2021-08-28 23:45:00,14.0,12.76,NaN,0.6,113.0,66.4,87.0,29.89,0.76,...,0.04,0.05,19.0,0.26,76.0,25.0,10.0,4.0,NaN,0.72
3,2021-08-28 23:40:00,NaN,NaN,NaN,0.6,151.0,66.5,87.0,29.89,0.76,...,0.04,0.05,19.0,0.25,76.0,25.0,10.0,4.0,99.0,0.72
4,2021-08-28 23:35:00,NaN,NaN,NaN,0.6,117.0,66.5,87.0,29.89,0.76,...,0.04,0.05,19.1,0.26,76.0,25.0,10.0,4.0,NaN,0.80

In [20]:
print(RawData.columns)

Index(['Timestamp', 'College Settlement > RSSI',
       'College Settlement > Battery',
       'College Settlement > Rain Bucket > Rain (in)',
       'College Settlement > Weather Station (MSO) > Wind Speed (mph) (MPH)',
       'College Settlement > Weather Station (MSO) > Wind Direction (deg) (°)',
       'College Settlement > Weather Station (MSO) > Temperature (F) (°F)',
       'College Settlement > Weather Station (MSO) > Relative Humidity (%) (%)',
       'College Settlement > Weather Station (MSO) > Barometric Pressure (inHg)',
       'College Settlement > Cell 1 > Water Level (m)',
       'College Settlement > Cell 1 > Temperature (C) (°C)',
       'College Settlement > Cell 1 > Pressure (psi) (psi)',
       'College Settlement > Cell 2 > Water Level (m) (m)',
       'College Settlement > Cell 2 > Pressure (psi) (psi)',
       'College Settlement > Cell 2 > Temperature (C) (°C)',
       'College Settlement > Cell 3 > Water Level (m) (m)',
       'College Settlement > Cell 3 > Pressure (psi) (psi)',
       'College Settlement > Cell 3 > Temperature (C) (°C)',
       'College Settlement > Flume > Water Level (m) (m)',
       'College Settlement > Flume > Pressure (psi) (psi)',
       'College Settlement > Flume > Temperature (C) (°C)',
       'College Settlement > Pyronometer (W/m^2) > Radiation (W/m²)',
       'College Settlement > Cell 1 > Water Level (cm) (cm)',
       'College Settlement > Cell 2 > Water Level (cm) (cm)',
       'College Settlement > Cell 3 > Water Level (cm) (cm)',
       'College Settlement > Flume > Water Level (cm) (cm)',
       'College Settlement > Statistics > Station Health (%)',
       'College Settlement: Outflow (L/sec)'],
      dtype='object')

In [21]:
RawData.columns = ['Date/Time', 'College Settlement > RSSI',
       'College Settlement > Battery', 'CS_Rain', 'CS_WindSpeed',
       'CS_WindDirection', 'CS_Temp', 'CS_Humidity', 'CS_BaroPress',
       'CS_C1Level', 'CS_C1Temp', 'CS_C1Pressure', 'CS_C2Level', 
       'CS_C2Pressure', 'CS_C2Temp','CS_C3Level',  'CS_C3Pressure','CS_C3Temp',
       'CS_FlumeLevel',  'CS_FlumePress', 'CS_FlumeTemp','CS_Radiation',
       'College Settlement > Cell 1 > Water Level (cm) (cm)',
       'College Settlement > Cell 2 > Water Level (cm) (cm)',
       'College Settlement > Cell 3 > Water Level (cm) (cm)',
       'College Settlement > Flume > Water Level (cm) (cm)',
       'College Settlement > Statistics > Station Health (%)', 'CS_Outflow']

ModData = RawData
ModData.head()

,Date/Time,College Settlement > RSSI,College Settlement > Battery,CS_Rain,CS_WindSpeed,CS_WindDirection,CS_Temp,CS_Humidity,CS_BaroPress,CS_C1Level,...,CS_FlumeLevel,CS_FlumePress,CS_FlumeTemp,CS_Radiation,College Settlement > Cell 1 > Water Level (cm) (cm),College Settlement > Cell 2 > Water Level (cm) (cm),College Settlement > Cell 3 > Water Level (cm) (cm),College Settlement > Flume > Water Level (cm) (cm),College Settlement > Statistics > Station Health (%),CS_Outflow
0,2021-08-28 23:55:00,NaN,NaN,NaN,0.6,126.0,66.5,87.0,29.89,0.76,...,0.04,0.05,19.0,0.26,76.0,25.0,10.0,4.0,NaN,0.72
1,2021-08-28 23:50:00,NaN,NaN,NaN,0.6,114.0,66.5,87.0,29.89,0.76,...,0.04,0.05,19.0,0.26,76.0,25.0,10.0,4.0,99.4,0.72
2,2021-08-28 23:45:00,14.0,12.76,NaN,0.6,113.0,66.4,87.0,29.89,0.76,...,0.04,0.05,19.0,0.26,76.0,25.0,10.0,4.0,NaN,0.72
3,2021-08-28 23:40:00,NaN,NaN,NaN,0.6,151.0,66.5,87.0,29.89,0.76,...,0.04,0.05,19.0,0.25,76.0,25.0,10.0,4.0,99.0,0.72
4,2021-08-28 23:35:00,NaN,NaN,NaN,0.6,117.0,66.5,87.0,29.89,0.76,...,0.04,0.05,19.1,0.26,76.0,25.0,10.0,4.0,NaN,0.80

In [22]:
ModData['CS_FlumeFlow_calculated'] =  0.00396436 -0.07231968 * np.power(ModData.CS_FlumeLevel, 0.5) + 79.89379128 * np.power(ModData.CS_FlumeLevel, 1.5) + 900.3765227 * np.power(ModData.CS_FlumeLevel, 2.5)
ModData['Gate stage'] = 'Open'


ModData.to_csv('C:\\Users/mkhosrav/Data Modification/02 - Raw Data - Modified/20210729 - 20210828 College Settlement Logger Data_modified.csv', index = False)
ModData.head()

,Date/Time,College Settlement > RSSI,College Settlement > Battery,CS_Rain,CS_WindSpeed,CS_WindDirection,CS_Temp,CS_Humidity,CS_BaroPress,CS_C1Level,...,CS_FlumeTemp,CS_Radiation,College Settlement > Cell 1 > Water Level (cm) (cm),College Settlement > Cell 2 > Water Level (cm) (cm),College Settlement > Cell 3 > Water Level (cm) (cm),College Settlement > Flume > Water Level (cm) (cm),College Settlement > Statistics > Station Health (%),CS_Outflow,CS_FlumeFlow_calculated,Gate stage
0,2021-08-28 23:55:00,NaN,NaN,NaN,0.6,126.0,66.5,87.0,29.89,0.76,...,19.0,0.26,76.0,25.0,10.0,4.0,NaN,0.72,0.916771,Open
1,2021-08-28 23:50:00,NaN,NaN,NaN,0.6,114.0,66.5,87.0,29.89,0.76,...,19.0,0.26,76.0,25.0,10.0,4.0,99.4,0.72,0.916771,Open
2,2021-08-28 23:45:00,14.0,12.76,NaN,0.6,113.0,66.4,87.0,29.89,0.76,...,19.0,0.26,76.0,25.0,10.0,4.0,NaN,0.72,0.916771,Open
3,2021-08-28 23:40:00,NaN,NaN,NaN,0.6,151.0,66.5,87.0,29.89,0.76,...,19.0,0.25,76.0,25.0,10.0,4.0,99.0,0.72,0.916771,Open
4,2021-08-28 23:35:00,NaN,NaN,NaN,0.6,117.0,66.5,87.0,29.89,0.76,...,19.1,0.26,76.0,25.0,10.0,4.0,NaN,0.80,0.916771,Open

In [13]:
ModData2 = pd.read_csv('C:\\Users/mkhosrav/Data Modification/02 - Raw Data - Modified/20180801 - 20181031 College Settlement Logger Data_modified.csv')
#ModData2.head()

In [14]:
ModData2.loc[(ModData2['CS_FlumeFlow_calculated'] == 'f') & (ModData2['CS_FlumeFlow_calculated'] < 0.08562995), 'CS_FlumeFlow_calculated'] = 0.0
ModData2.to_csv('C:\\Users/mkhosrav/Data Modification/02 - Raw Data - Modified/20180801 - 20181031 College Settlement Logger Data_modified22.csv', index=False)

TypeError: '<' not supported between instances of 'str' and 'float'

In [ ]:
ModData2.loc[ModData2['CS_FlumeFlow_calculated'] == 'f' & ModData2['CS_FlumeFlow_calculated'] < 0.08562995, 'CS_FlumeFlow_calculated'] = 0.0

In [5]:
x_df = ModData2[['CS_FlumeFlow_calculated', 'College Settlement > Flume > Water Level (cm) (cm)']]
x_df.loc[x_df['CS_FlumeFlow_calculated'] != 'f' & x_df['CS_FlumeFlow_calculated'] < 0.08562995, 'CS_FlumeFlow_calculated'] = 0.0

TypeError: Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]

In [248]:
x_np = x_df.values
x_np

array([[0.54693335, 3.        ],
       [0.54693335, 3.        ],
       [0.91677124, 3.        ],
       ...,
       [0.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ]])

In [236]:
#test1 = ModData2[(ModData2.CS_FlumeFlow_calculated != 'f') & (ModData2.CS_FlumeFlow_calculated < 0.08562995)]

In [237]:
#ModData['CS_FlumeFlow_calculated'].values[ModData['CS_FlumeFlow_calculated'] < 0.085629949] = 0
ModData2['CS_FlumeFlow_calculated'].values[ModData2['CS_FlumeFlow_calculated'] < 0.08562995] = 0
ModData2['College Settlement > Flume > Water Level (cm) (cm)'].values[ModData2['CS_FlumeFlow_calculated'] < 0.08562995] = 0
ModData2['CS_FlumeLevel'].values[ModData2['CS_FlumeFlow_calculated'] < 0.08562995] = 0
ModData2['CS_FlumePress'].values[ModData2['CS_FlumeFlow_calculated'] < 0.08562995] = 0

#ModData2['CS_Outflow'].values[ModData2['CS_FlumeTemp'] < 0.01 & ModData2['CS_FlumeLevel'] > 0.1] = 0

#ModData.to_csv('C:\\Users/mkhosrav/Data Modification/02 - Raw Data - Modified/20200828 - 20200912 College Settlement Logger Data_modified.csv', index = False)
ModData2.to_csv('C:\\Users/mkhosrav/Data Modification/02 - Raw Data - Modified2/20180801 - 20181031 College Settlement Logger Data_modified.csv', index=False)

In [238]:
#print(ModData2.columns)

In [239]:
WeaData=ModData2[['Date/Time', 'CS_WindSpeed', 'CS_WindDirection', 'CS_Temp', 'CS_Humidity', 'CS_BaroPress', 'CS_Rain', 'CS_Radiation', 'CS_Outflow']]

In [240]:
WeaData.to_csv('C:\\Users/mkhosrav/Data Modification/03 - Weather Station Modified/20180801 - 20181031_CSWX_Hydroserver.csv', index=False)

In [241]:
WatData=ModData2[['Date/Time', 'CS_Rain','CS_C1Level', 'CS_C1Temp', 'CS_C1Pressure', 'CS_C2Level', 'CS_C2Temp',
       'CS_C2Pressure', 'CS_C3Level', 'CS_C3Temp', 'CS_C3Pressure',
       'CS_FlumeLevel', 'CS_FlumeTemp', 'CS_FlumePress', 'CS_Outflow', 'CS_FlumeFlow_calculated', 'Gate stage']]

In [242]:
WatData.to_csv('C:\\Users/mkhosrav/Data Modification/04 - Water Quantity Modified/20180801 - 20181031_CSWQ_Hydroserver.csv', index=False)